/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoo.janelas;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import trabalhopoo.controllers.LoginController;
import trabalhopoo.controllers.ProductRepo;

/**
 *
 * @author rodri
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form JanelaInicial
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        updateMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private LoginController control = new LoginController();

    private void updateMenus() {

        System.out.println("Updating menus...");

        boolean isLogged = control.isLogado();

        System.out.println("Is logged in: " + isLogged);

        mnuItemLogin.setEnabled(!control.isLogado());
        mnuItemLogout.setEnabled(control.isLogado());
        mnuProfile.setEnabled(control.isLogado());
        mnuArchive.setEnabled(control.isLogado());
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgG4U = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchive = new javax.swing.JMenu();
        mnuItemOpen = new javax.swing.JMenuItem();
        mnuItemRecovery = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuItemSave = new javax.swing.JMenuItem();
        mnuItemDelete = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        mnuItemChgPswrd = new javax.swing.JMenuItem();
        mnuItemChgUser = new javax.swing.JMenuItem();
        mnuLogin = new javax.swing.JMenu();
        mnuItemLogin = new javax.swing.JMenuItem();
        mnuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));

        imgG4U.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhopoo/images/G4UDeitadoGrande1.png"))); // NOI18N
        imgG4U.setPreferredSize(new java.awt.Dimension(250, 150));
        imgG4U.setRequestFocusEnabled(false);

        mnuArchive.setMnemonic('a');
        mnuArchive.setText("Archive");

        mnuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemOpen.setMnemonic('o');
        mnuItemOpen.setText("Open");
        mnuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemOpenActionPerformed(evt);
            }
        });
        mnuArchive.add(mnuItemOpen);

        mnuItemRecovery.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemRecovery.setText("Recovery");
        mnuItemRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRecoveryActionPerformed(evt);
            }
        });
        mnuArchive.add(mnuItemRecovery);
        mnuArchive.add(jSeparator1);

        mnuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemSave.setMnemonic('s');
        mnuItemSave.setText("Save");
        mnuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSaveActionPerformed(evt);
            }
        });
        mnuArchive.add(mnuItemSave);

        mnuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemDelete.setMnemonic('d');
        mnuItemDelete.setText("Delete");
        mnuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDeleteActionPerformed(evt);
            }
        });
        mnuArchive.add(mnuItemDelete);

        jMenuBar1.add(mnuArchive);

        mnuProfile.setText("Profile");

        mnuItemChgPswrd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemChgPswrd.setText("Change Password");
        mnuItemChgPswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemChgPswrdActionPerformed(evt);
            }
        });
        mnuProfile.add(mnuItemChgPswrd);

        mnuItemChgUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemChgUser.setText("Change Username");
        mnuItemChgUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemChgUserActionPerformed(evt);
            }
        });
        mnuProfile.add(mnuItemChgUser);

        jMenuBar1.add(mnuProfile);

        mnuLogin.setMnemonic('l');
        mnuLogin.setText("Login");

        mnuItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemLogin.setMnemonic('l');
        mnuItemLogin.setText("Login");
        mnuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLoginActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuItemLogin);

        mnuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemLogout.setMnemonic('l');
        mnuItemLogout.setText("Logout");
        mnuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoutActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuItemLogout);

        jMenuBar1.add(mnuLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(imgG4U, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgG4U, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoutActionPerformed
        control.signOut();
        updateMenus();
    }//GEN-LAST:event_mnuItemLogoutActionPerformed

    private void mnuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDeleteActionPerformed
        ProductRepo inventory = new ProductRepo();
        String nameArq = JOptionPane.showInputDialog(this, "Insira o nome do arquivo a ser excluído:");
        if (nameArq != null && !nameArq.isEmpty()) {
            // Chamar a função para deletar o arquivo
            inventory.deleteFileByName(nameArq);
        } else {
            // Informar ao usuário que o nome do arquivo é inválido
            JOptionPane.showMessageDialog(this, "Nome do arquivo inválido. Nenhuma ação foi realizada.");
        }
    }//GEN-LAST:event_mnuItemDeleteActionPerformed

    private void mnuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLoginActionPerformed
        JDialog loginWindow = new LoginWindow(this, true);
        loginWindow.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                updateMenus();
            }
        });
        loginWindow.setVisible(true);
    }//GEN-LAST:event_mnuItemLoginActionPerformed

    private void mnuItemChgPswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemChgPswrdActionPerformed
        JDialog changeWindow = new ChangePswrdWindow(this, true);

        changeWindow.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                updateMenus();
            }
        });
        changeWindow.setVisible(true);
    }//GEN-LAST:event_mnuItemChgPswrdActionPerformed

    private void mnuItemChgUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemChgUserActionPerformed
        JDialog changeWindow = new ChangeUserWindow(this, true);
        changeWindow.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                updateMenus();
            }
        });
        changeWindow.setVisible(true);
    }//GEN-LAST:event_mnuItemChgUserActionPerformed

    private void mnuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemOpenActionPerformed
        new ProductsWindow(this, true).setVisible(true);
    }//GEN-LAST:event_mnuItemOpenActionPerformed

    private void mnuItemRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRecoveryActionPerformed
        String nameArq = JOptionPane.showInputDialog("Prefix", "data");
        ProductRepo inventory = new ProductRepo();
        inventory.recover(nameArq);
    }//GEN-LAST:event_mnuItemRecoveryActionPerformed

    private void mnuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSaveActionPerformed
        String nameArq = JOptionPane.showInputDialog("Prefix", "data");
        ProductRepo inventory = new ProductRepo();
        inventory.save(nameArq);
    }//GEN-LAST:event_mnuItemSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatMacDarkLaf.setup();
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgG4U;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuArchive;
    private javax.swing.JMenuItem mnuItemChgPswrd;
    private javax.swing.JMenuItem mnuItemChgUser;
    private javax.swing.JMenuItem mnuItemDelete;
    private javax.swing.JMenuItem mnuItemLogin;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenuItem mnuItemOpen;
    private javax.swing.JMenuItem mnuItemRecovery;
    private javax.swing.JMenuItem mnuItemSave;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenu mnuProfile;
    // End of variables declaration//GEN-END:variables
}
